print("hello would you like to make a mad lib today? ")
print("i dont care if you want to or not were making one!")
pronoun = input("Give me a Pro Noun ")
verb1 = input("Give me a verb ending in ing ")
adj1 = input("Give me an adjective ")
element1 = input("Give me an element ")
verb2 = input("Give me another verb but this time in the past tense ")
place = input("Give me a place ")
adverb1 = input("Give me an adverb ending in ly ")
weapon = input("Give me a weapon ")
adj2 = input("Give me one more adjective ending in ly ")
verb3 = input("Now one more past tense verb ")
print(f" \n - - - \n \n One day on a moon far far away {pronoun} was {verb1} back from a mission. \n All of the sudden a {adj1} {element1} monster {verb2} infront of {pronoun}. \n {pronoun} {verb3} all the way to {place}. \n {adverb1} the monster followed so {pronoun} pulled out their {weapon} amd {adj2} defeated the monster. \n {pronoun} {verb3} all the way back to the moon and lived happily ever after. \n The End.")
